name: CI

on:
  push:
    branches:
      - devel

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libncurses-dev \
            libleveldb-dev \
            libsnappy-dev

      - name: Build project
        run: make
